### ISSUE TITLE
Upload pattern fails with internal server error / Permission denied: '/usr/src/app/media/mockuser'

### ISSUE THREAD

**Issue by torxes** [Qiskit-Extensions/quantum-serverless#1231]
### Steps to reproduce the problem

Versions:
```
...
qiskit==1.0.1
qiskit-ibm-provider==0.10.0
qiskit-ibm-runtime==0.20.0
quantum-serverless==0.9.0
```

- Deploy quantum serverless on a non-IBM cluster.
- Upload a pattern (Follow https://qiskit-extensions.github.io/quantum-serverless/getting_started/basic/01_running_program.html#Running-a-QiskitPattern-remotely)

### What is the current behavior?
Client error:

```
# python dispatch.py 
Traceback (most recent call last):
  File "/data/.../quantum-serverless/pattern/dispatch.py", line 14, in <module>
    serverless.upload(pattern)
  File "/data/.../.pyenv/versions/quantum-serverless/lib/python3.11/site-packages/quantum_serverless/core/provider.py", line 434, in upload
    response = self._job_client.upload(program)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/.../.pyenv/versions/quantum-serverless/lib/python3.11/site-packages/quantum_serverless/core/job.py", line 482, in upload
    response_data = safe_json_request(
                    ^^^^^^^^^^^^^^^^^^
  File "/data/.../.pyenv/versions/quantum-serverless/lib/python3.11/site-packages/quantum_serverless/utils/json.py", line 104, in safe_json_request
    raise QuantumServerlessException(
quantum_serverless.exception.QuantumServerlessException: 
| Message: Http bad request.
| Code: 500
```

Logs from gateway pod:
``` 
ERROR 2024-02-23 10:54:13,227 services.py:64 : Exception was caught saving the program [my-first-pattern] by [mockuser] 
Error trace: [Errno 13] Permission denied: '/usr/src/app/media/mockuser'
ERROR 2024-02-23 10:54:13,228 log.py:241 : Internal Server Error: /api/v1/programs/upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InternalServerErrorException is not JSON serializable
```

### What is the expected behavior?

1) The pattern upload succeeds.
2) Handle error serialization.

**Comment by torxes** [comment]
The root cause - from what I understand - seems to be that the securityContext is to applicable for local hostpath PVs therefore the upload directory is not writeable and the resulting error. I was able to work around that by editing the gateway deployment with an init container that changes the ownership:

```
        - command:                                                                                                                                                                                                                                
          - sh                                                                                                                                                                                                                                    
          - -c                                                                                                                                                                                                                                    
          - chown -R 1000:100 /usr/src/app/media                                                                                                                                                                                                  
          image: busybox                                                                                                                                                                                                                          
          imagePullPolicy: Always                                                                                                                                                                                                                 
          name: volume-mount-ownership                                                                                                                                                                                                                 
          resources: {}                                                                                                                                                                                                                           
          securityContext:                                                                                                                                                                                                                        
            runAsUser: 0                                                                                                                                                                                                                          
          terminationMessagePath: /dev/termination-log                                                                                                                                                                                            
          terminationMessagePolicy: File                                                                                                                                                                                                          
          volumeMounts:                                                                                                                                                                                                                           
          - mountPath: /usr/src/app/media/                                                                                                                                                                                                        
            name: gateway-pv-storage       
```

**Comment by akihikokuroda** [comment]
@torxes I'm curious.  What kind of kubernetes environment are you working on?

**Comment by psschwei** [comment]
Also, what type of storage are you using?

**Comment by torxes** [comment]
> @torxes I'm curious. What kind of kubernetes environment are you working on?

It's a custom [Gardner](https://gardener.cloud/adopter) based cluster we are using internally. I am not too familiar with the quirks of k8s. Any specific characteristic you are interested in? From what I understand this might also be reproducible on a minikube cluster.

> Also, what type of storage are you using?

In general our Gardner deployment provides a CSI depending on the hyperscaler. In this particular issue, the pvcs deployment in the falls back to host local path. 

```
Name:            gateway-volume
Labels:          app.kubernetes.io/managed-by=Helm
                 type=local
Annotations:     meta.helm.sh/release-name: quantum-serverless
                 meta.helm.sh/release-namespace: default
                 pv.beta.kubernetes.io/gid: 100
                 pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    manual
Status:          Bound
Claim:           default/gateway-claim
Reclaim Policy:  Retain
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /mnt/data/tmp
    HostPathType:  
```

**Comment by akihikokuroda** [comment]
@torxes Thanks for info.  The current helm template has the hardcode storage class name.  It's probably impossible to cover every environment where this is deployed.  We can make the storage class name configurable in the values.yaml file or in the helm install command options.  So you can create / deploy your own storage class and the quantum serverless use it.  WDYT?

**Comment by psschwei** [comment]
> > Also, what type of storage are you using?
> 
> In general our Gardner deployment provides a CSI depending on the hyperscaler. In this particular issue, the pvcs deployment in the falls back to host local path.
 
Thanks. One thing to note is that using `hostPath` is generally not recommended due to the [extra security risks](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath)... though we may want to think about what type(s) of storage we want to recommend folks use and plan accordingly for these types of permissions issues.

**Comment by torxes** [comment]
> We can make the storage class name configurable in the values.yaml file or in the helm install command options. So you can create / deploy your own storage class and the quantum serverless use it. WDYT?

I guess in the end the goal is to have an easy deployment that makes getting started easy. My thinking was to keep the current fallback to the manual storage class and add the init container in that case. In addition I would probably suggest some documentation that covers some aspects that need to be adjusted for "productive" deployment such as making sure that configuring a storage class reasonable for the environment.

> Thanks. One thing to note is that using `hostPath` is generally not recommended due to the [extra security risks](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath)... though we may want to think about what type(s) of storage we want to recommend folks use and plan accordingly for these types of permissions issues.

For further testing I will adjust the storage class in the deployment manually, but it would already be great help if it'd be configurable as @akihikokuroda suggested :)

**Comment by djmcgreal-cc** [comment]
My workaround:
```yaml
    platform: kind # even though it isn't, this gets us a dynamic PVC that we must later take control of..
    cosEnabled: false # get a dynamic PVC
```

Add `--post-renderer 'yq' --post-renderer-args '--from-file' --post-renderer-args 'update-gateway-storageclass.yq'` to `helm`.

Where _update-gateway-storageclass.yq_ is:
```yq
(
  select(.metadata.name == "gateway-claim") 
    | .spec.storageClassName = "network"
) // . 
```

**Comment by matteoacrossi** [comment]
I'm having the same problem when deploying 0.21.1 to a Azure AKS cluster using Helm as in the qiskit-serverless documentation. How do I go about setting the storage in the right way? I see the following with `kubectl describe pvc`:

```
Name:          gateway-claim
Namespace:     default
StorageClass:  manual
Status:        Bound
Volume:        gateway-volume
Labels:        app.kubernetes.io/managed-by=Helm
Annotations:   meta.helm.sh/release-name: qiskit-serverless
               meta.helm.sh/release-namespace: default
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       gateway-76d4b8cd64-hqjnw
               scheduler-7f887cd5c8-s9zbh
Events:        <none>
```

**Comment by matteoacrossi** [comment]
Indeed I managed to solve the issue by using this configuration for the PVC. `default` is the way for AKS, and no need to create a `PersistentVolume`

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-claim
spec:
  storageClassName:  default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
