### ISSUE TITLE
Dockerfile: add version support to dockerfiles in order to use nightly, stable, latest or versioned images

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#434]
### What is the expected enhancement?

Add version support to dockerfiles in order to use nightly, stable, latest or versioned images

---

By @psschwei 

assuming you meant the compose file, we could do something like:
```yaml
services:
  jupyter:
    container_name: qs-jupyter
    image: qiskit/quantum-serverless-notebook:${VERSION:-0.0.6}-py39
    ...
```

and then if you wanted to run nightly do something like VERSION=nightly docker compose up
