### ISSUE TITLE
Add dev and regular docker-compose files

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#83]
### What is the expected enhancement?

Split docker compose into 2 version:
1. dev version which builds images from file and current project
2. version with images from `qiskit` dockerhub with latest commit for user to play around 

Something like this

Dev
```yaml
services:
  jupyter:
    container_name: qs-jupyter
    build:
      context: ./
      dockerfile: infrastructure/docker/Dockerfile-notebook
```

Regular
```yaml
services:
  jupyter:
    container_name: qs-jupyter
    image: qiskit/quantum-serverless-notebook:latest
```
