### ISSUE TITLE
Trace entries accessing collector when trace is disabled

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#912]
### Steps to reproduce the problem
Install Quantum-middleware without enabling distributed tracing (default). The following setting should disable all distributed tracing entry accessing to the collector
```
gateway:
  application:
    ray:
      openTelemetry: false
      openTelemetryCollector
        enabled: 0

jupyter:
  openTelemetryCollector:
    enabled: 0
```
The Ray head node pod log (-c ray-head-logs) has error entries

### What is the current behavior?
Some trace entry in the Ray cluster trying to access to the collector

### What is the expected behavior?
Any trace entry should not trying to access to the collector
